version: '3.9'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"    

  nginx:
    container_name: nginx-container
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf 
    ports:
      - "80:80"  
    depends_on:
      - docker-server  

  docker-server:
    container_name: docker-server
    restart: always
    build: .
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - PORT=6000
    ports:
      - 6000:6000    
